Q1. What are the benefits of the built-in array package, if any?

The Python array's scope is limited  as it is quite restricted. Though the restriction stays in we can easily convert a Python array into a Python list. The example has been given below.

In [4]:
try:
    from array import array # Importing built-in array library
    arr = array('u', 'abcdefg')  # "u "means this array contains unicode characters
    my_list = arr.tolist()
    print(my_list)
except:
    print('conversion from array to list')

['a', 'b', 'c', 'd', 'e', 'f', 'g']


Python built-in array is restricted, and we rarely use it. But oin the other hand, if something is restricted it must bring some benefits. In this case, the benefit is that Python built-in array has smaller size then Python list. Let's go through an example to understand this. A Python List with 200,000 integers is created. Then, it is converted into Python Array.

In [6]:
try:
    from array import array 
    large_list = list(range(0,200000))
    large_array = array("I", large_list)
    
    print(large_list.__sizeof__())
    print(large_array.__sizeof__())
except:
    print("detection of length of array and list")

1600040
800064


It can be seen  from the above example that the size of the array is only about the half of the size of the list, even smaller than half. This is because the type code of the array is fixed and the number of bytes of each item is also fixed. It loses some flexibility but has less overhead. So, Python Array uses less memory size than Python List. It can directly handle arithmetic operations and alos saves time.

Q2. What are some of the array package's limitations?

The array package's limitations are:

It contains the value of the same data type.
We need to import the array first before we work with the array.
It is suitable for storing shorter sequence of data items.

Q3. Describe the main differences between the array and numpy packages.

NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of a Python array will create a new array and delete the original.

NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than using Python’s built-in sequences or arrays.

In order to efficiently use much (perhaps even most) of today’s scientific and mathematical Python-based software, just knowing how to use Python’s built-in sequence or array types is not sufficient, one also needs to know how to use NumPy arrays.

Q4. Explain the distinctions between the empty, ones, and zeros functions.

np.empty() returns a new array of given shape and type with random values. syntax is 

numpy.empty(shape, dtype = float/ int, order 'c')

In [10]:
try:
    import numpy as np
    a = np.empty(2, dtype = int)
    print("\n Matrix a is : \n", a)
    
    b = np.empty([2,2], dtype = int)
    print("\n Matrix b is : \n ", b)
    
    c = np.empty([4,4], dtype = int)
    print("\n Matrix c is : \n", c)
except:
    print('empty function in numpy')


 Matrix a is : 
 [0 0]

 Matrix b is : 
  [[-1690364453   281026027]
 [ -935327867  1450506963]]

 Matrix c is : 
 [[   0    0    0    0]
 [   0    0    0    0]
 [   0    0 1336    0]
 [   0    0    0    0]]


The numpy.zeros() function returns a new array of given shape and type, with zeros. Syntax is:

numpy.zeros(shape, dtype = None, order = 'C')

In [13]:
try:
    import numpy as np
    a = np.zeros(2, dtype = int)
    print("\n Matrix a is : \n", a)
    
    b = np.zeros([3,3], dtype = int)
    print("\n Matrix b is : \n ", b)
    
    c = np.zeros([5,5], dtype = int)
    print("\n Matrix c is : \n", c)
except:
    print('empty function in numpy')


 Matrix a is : 
 [0 0]

 Matrix b is : 
  [[0 0 0]
 [0 0 0]
 [0 0 0]]

 Matrix c is : 
 [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


The numpy.ones() function returns a new array of given shape and type, with ones.
 
Syntax is : numpy.ones(shape, dtype = None, order = 'C') 

In [16]:
try:
    import numpy as np
    a = np.ones(1, dtype = int)
    print("\n Matrix a is : \n", a)
    
    b = np.ones([3,3], dtype = int)
    print("\n Matrix b is : \n ", b)
    
    c = np.ones([6,6], dtype = int)
    print("\n Matrix c is : \n", c)
except:
    print('empty function in numpy')


 Matrix a is : 
 [1]

 Matrix b is : 
  [[1 1 1]
 [1 1 1]
 [1 1 1]]

 Matrix c is : 
 [[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]


Q5. In the from function function, which is used to construct new arrays, what is the role of the callable
argument?

Generally a callable is something that can be called. This built-in callable method in Python checks and returns True if the object passed appears to be callable, otherwise False.
Syntax:
callable(object)
The callable() method takes only one argument, an object and returns one of the two values:
returns True, if the object appears to be callable.
returns False, if the object is not callable.
Let us see both senarios.

In [131]:
 # When an object is callable
try:
    def test():
        
        return 43
    a = test
    print(callable(a))
    
    b = [1,2,3,4,5]
    print(callable(b))
except:
    print('Object is callable')

True
False


From the above example, we see in the first case when an object is passed in the callable() method, it returns True. It is so because a is an object to the callable function test. But in the second case b is absolutely not a callable object, so the result is False.

In [132]:
# When an object is not callable

try:
    class test1():
        def func(self):
            print([1,2,3,4,5])
    print(callable(test1))
    obj = test1()
    obj()
except:
    print('object is not callable')
        

True
object is not callable


The callable() method returns True suggesting that the test1 class is callable, but the instance of test1 is not callable() and it returns a runtime error but here that runtime error did not arise as it is handled by the exception handling in the except block.

Q6. What happens when a numpy array is combined with a single-value operand (a scalar, such as
an int or a floating-point value) through addition, as in the expression A + n?

When a numpy array is cobined with a single-value operand or a scalar( like an integer or floating point number ) then it will be cobined with each and every element in that array and will produce a new numpy array either in case of addition, subtraction, division or multiplication. One example has been set over here in terms of addition.

In [137]:
# Numerical operations on Numpy arrays

try:
    import numpy as np
    
    l = [1.2, 2.3, 3.4,4.5, 5.6, 6.7,7.8, 8.9,9.1]
    A = np.array(l)
    n = 2
    n1 = 3.14
    print(A + n)
    print(A + n1)
    
except:
    print('Numerical ops on numpy arrays')

[ 3.2  4.3  5.4  6.5  7.6  8.7  9.8 10.9 11.1]
[ 4.34  5.44  6.54  7.64  8.74  9.84 10.94 12.04 12.24]


Q7. Can array-to-scalar operations use combined operation-assign operators (such as += or *=)?
What is the outcome?

Array-to-scalar operations can use combined operation-assign operators( Such as : + = or *=).
Some examples are given here.

In [100]:
# Example of += operator
try:
    a = 16
    a += 27
    print(a)
except:
    print('assignment operator')

43


The above example's outcome i.e, a += is same as a = a + and this will be shown in the following example.

In [101]:
try:
    a = 16
    a = a + 27
    print(a)
except:
    print('assignment operator')

43


In [102]:
# example of *= assignment operator

try:
    a = 16
    a *= 27
    print(a)
except:
    print('assignment operator')

432


The above example's outcome i.e, a *= is equivalent to a = a * 

In [104]:
try:
    a = 16
    a = a *27
    print(a)
except:
    print('assignment operator')

432


Q8. Does a numpy array contain fixed-length strings? What happens if you allocate a longer string to
one of these arrays?

NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original. The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

The dtype of any numpy array or ndarray containing string values is the maximum length of any string present in the array. Once set, it will only be able to store new string having length not more than the maximum length at the time of the creation. If we try to reassign some another string value having length greater than the maximum length of the existing elements, it simply discards all the values beyond the maximum length. But we can fix this problem by simply assigning dtype = 'object'. Let's see throuh an example.

In [113]:
try:
    import numpy as np
    county = np.array(['Hampshire', 'Derbyshire', 'Essex', ' ', 'Middlesex', 'Yorkshire'])
    print(county)
    
    county[county ==' '] = 'New Hampshire'
    print(county)
except:
    print('Assignment aribtrary string in ndarray')

['Hampshire' 'Derbyshire' 'Essex' ' ' 'Middlesex' 'Yorkshire']
['Hampshire' 'Derbyshire' 'Essex' 'New Hampsh' 'Middlesex' 'Yorkshire']


 As we can see from the first output the maximum length of any string length in the given array is 9. And we are trying to assign a string which has greater length at the place of missing value in the array. The neew string with greater length is 'New Hampshire'. As we can see in the output, ‘New Hampsh’ has been assigned rather than ‘New Hampshire’ because of the limitation to the length. Now, let’s see how we can overcome this problem.

In [114]:
try:
    import numpy as np
    county = np.array(['Hampshire', 'Derbyshire', 'Essex', ' ', 'Middlesex', 'Yorkshire'], dtype = 'object')
    print(county)
    
    county[county ==' '] = 'New Hampshire'
    print(county)
except:
    print('Assignment aribtrary string in ndarray')

['Hampshire' 'Derbyshire' 'Essex' ' ' 'Middlesex' 'Yorkshire']
['Hampshire' 'Derbyshire' 'Essex' 'New Hampshire' 'Middlesex' 'Yorkshire']


 Now we can see from the output that we have been able to assign an arbitrary length of string to the given array object by just simpluy assigning dtype = 'object'

Q9. What happens when you combine two numpy arrays using an operation like addition (+) or
multiplication (*)? What are the conditions for combining two numpy arrays?

If we multiply two numpy arrays in terms of combination it returns a numpy array of the same shape with values resulting from multiplying values in each array elementwise. It should be noted that both the arrays need to have the same dimensions. Again if we concatenate two numpy arrays we actually join a sequence of arrays along an existing axis.The arrays must have the same shape, except in the dimension corresponding to axis (the first, by default).

The conditions for combining two numpy arrays incase of multiplication are that we can only multiply two array matrices if their dimensions are compatible. That menas the number of columns in the first matrix should be the same as the number of rows in the second matrix.

In [115]:
# Numerical operations on Numpy arrays

try:
    import numpy as np
    
    l = [1.2, 2.3, 3.4,4.5, 5.6, 6.7,7.8, 8.9,9.1]
    r = np.array(l)
    print(r +3.14)
    print(r * 4)
except:
    print('Numerical ops on numpy arrays')

[ 4.34  5.44  6.54  7.64  8.74  9.84 10.94 12.04 12.24]
[ 4.8  9.2 13.6 18.  22.4 26.8 31.2 35.6 36.4]


There are so may other ways or methods existing by which we can cobine two numpy arrays. Such as concatenate method, append method, stack method, vstack method and many more. Some of those are exemplified here.

In [128]:
# append() method , concatenate () method, stack() method, vstack()method, hstack() method, column_stack() method
try:
    import numpy as np
    
    a1 = [1,2,3,4,5]
    a2 = [6,7,8,9,10]
    
    new_array = np.append(a1, a2)
    print(new_array)
    
    new_array = np.concatenate([a1, a2])
    print(new_array)
    
    new_array = np.stack([a1, a2])
    print(new_array)
    
    new_array = np.vstack([a1, a2])
    print(new_array)
    
    new_array = np.hstack([a1, a2])
    print(new_array)
    
    new_array = np.column_stack([a1, a2])
    print(new_array)
    
except:
    print('various methods of combining np arrays')
    

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


Q10. What is the best way to use a Boolean array to mask another array?

The best way to use a Boolean array to mask another array is by masking operation where to select these values from the array we can simply index on this Boolean array. The example is given below.

In [89]:
try:
    a = [[5, 6, 3, 9],
         [1, 5, 8, 3],
         [2, 4, 7, 8]]
    import numpy as np
    x1 = np.array([[5, 6, 3, 9],
                   [1, 5, 8, 3],
                   [2, 4, 7, 8]], dtype = bool )
     
    print(x1)
except:
    print(" masking with boolean ")

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [90]:
try:
    a = [[5, 6, 3, 9],
         [1, 5, 8, 3],
         [2, 4, 7, 8]]
    import numpy as np
    x = np.array([[5, 6, 3, 9],
                 [1, 5, 8, 3],
                 [2, 4, 7, 8]], )
     
    print(x)
except:
    print(" masking with boolean ")

[[5 6 3 9]
 [1 5 8 3]
 [2 4 7 8]]


In [92]:
x < 5

array([[False, False,  True, False],
       [ True, False, False,  True],
       [ True,  True, False, False]])

In [88]:
x[x <5]

array([3, 1, 3, 2, 4])

The returned array is a one- dimensional array filled with all the values that meet the condition( where x < 5) in other words, all the values in positions at which the mask array is True.

Q11. What are three different ways to get the standard deviation of a wide collection of data using
both standard Python and its packages? Sort the three of them by how quickly they execute.

Three different ways to get the standard deviation of a wide collection of data using
both standard Python and its packages are :

Using the pstdev() Function of the statistics Module to Calculate the Standard Deviation of a List in Python
Using the std() Function of the NumPy Library to Calculate the Standard Deviation of a List in Python
Using the sum() Function and List Comprehension to Calculate the Standard Deviation of a List in Python

Let's see through the examples for each way.

In [145]:
# Using the pstdev() Function of the statistics Module to Calculate the Standard Deviation of a List in Python

try:
    import statistics
    l = [16,36,43,108,786,1008]
    
    print('List is : ' +str(l))
    std_dev = statistics.pstdev(l)
    print("The standard deviation of the given list is : " +str(std_dev))
except:
    print('pstdev function to calculate std dev')

List is : [16, 36, 43, 108, 786, 1008]
The standard deviation of the given list is : 405.02198157082233


In [146]:
# Using the std() Function of the NumPy Library to Calculate the Standard Deviation of a List in Python

try:
    import numpy as np
    l = [16,36,43,108,786,1008]
    
    print('List is : ' +str(l))
    std_dev = np.std(l)
    print("The standard deviation of the given list is : " +str(std_dev))
except:
    print('std function to calculate std dev')


List is : [16, 36, 43, 108, 786, 1008]
The standard deviation of the given list is : 405.02198157082233


In [148]:
# Using the sum() Function and List Comprehension to Calculate the Standard Deviation of a List in Python
try:
    import math
    l  = [16,36,43,108,786,1008]
    print('List is : ' +str(l))
    
    mean = sum(l)/len(l)
    var = sum((i-mean)**2 for i in l)/len(l)
    std_dev = math.sqrt(var)
    print("The standard deviation of the given list is : " +str(std_dev))
except:
    print('sum function and list comprehension to detect std dev')
    
    

List is : [16, 36, 43, 108, 786, 1008]
The standard deviation of the given list is : 405.02198157082233


In the example above, the math module is imported. It provides the sqrt() function to calculate the square root of a given value. Also, note that the function len() is also used. This function helps provide the length of the given list, for example, the number of elements in the list.
This method is based on the mathematical formula of standard deviation. First, we calculate the variance and then get its square root to find the standard deviation. This is lengthy process and takes a lot steps to execute the standard deviation.

But the first two methods are quicker as compared to the above method as both take less steps to execute standard deviation in the programme. In the first method,  the str() function converts the whole list and its standard deviation into a string because it can only be concatenated with a string and the second method uses Numpy which is a library widely used known as Numerical Python in Python.This library helps in dealing with arrays, matrices, linear algebra, and Fourier transform. These two methods only take a few steps to execute the standard deviation of a larger dataset. But since numpy library is widely used in Python and this library also helps in dealing with arrays, matrices, linear algebra, and Fourier transform so, using the std() function of the NumPy Library to calculate the Standard Deviation is preferable to using the pstdev() Function of the statistics Module to Calculate the Standard Deviation of a larger dataset in Python.

12.What is the dimensionality of a Boolean mask-generated array?

The returned array is a one- dimensional array filled with all the values that meet the condition in other words, all the values in positions at which the mask array is True. The example is given below.

In [95]:
try:
    a = [[5, 6, 3, 9],
         [1, 5, 8, 3],
         [2, 4, 7, 8]]
    import numpy as np
    x = np.array([[5, 6, 3, 9],
                 [1, 5, 8, 3],
                 [2, 4, 7, 8]], )
     
    print(x)
    print(x[x<4])
except:
    print(" masking with boolean ")

[[5 6 3 9]
 [1 5 8 3]
 [2 4 7 8]]
[3 1 3 2]


In [96]:
x < 4

array([[False, False,  True, False],
       [ True, False, False,  True],
       [ True, False, False, False]])

In [97]:
x[x< 4]

array([3, 1, 3, 2])